# Generated by Django 5.1.3 on 2025-06-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ghost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('pts', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('atk', models.IntegerField(default=0)),
                ('df', models.IntegerField(default=0)),
                ('spc', models.IntegerField(default=0)),
                ('agl', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('pts', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('atk', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50, unique=True)),
                ('userPassword', models.CharField(max_length=50)),
                ('tokenSession', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
