# Generated by Django 5.1.3 on 2025-06-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplerest11app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.AddField(
            model_name='user',
            name='atk',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='user',
            name='hp',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='user',
            name='pts',
            field=models.IntegerField(default=0),
        ),
    ]
