# Generated by Django 5.1.3 on 2025-06-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplerest11app', '0002_delete_player_user_atk_user_hp_user_pts'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghost',
            name='img',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
